CREATE TABLE Users(
idUser INTEGER NOT NULL AUTO_INCREMENT,
login VARCHAR(25) NOT NULL,
pwdUser VARCHAR(128) NOT NULL,
PRIMARY KEY(idUser)
)ENGINE=InnoDB;

CREATE TABLE Servers(
idServer INTEGER NOT NULL AUTO_INCREMENT,
nameServer VARCHAR(25) NOT NULL,
descServer TEXT,
idOwner INTEGER NOT NULL,
unjoinable BOOL DEFAULT 0,
PRIMARY KEY(idServer)
)ENGINE=InnoDB;

CREATE TABLE Role(
idRole INTEGER NOT NULL AUTO_INCREMENT,
nameRole VARCHAR(25) NOT NULL,
imgRole VARCHAR(25) NOT NULL,
PRIMARY KEY(idRole)
)ENGINE=InnoDB;

ALTER TABLE Servers
  ADD CONSTRAINT FOREIGN KEY (idOwner)
  REFERENCES Users(idUser)
  ON DELETE CASCADE;

CREATE TABLE Players(
idServer INTEGER NOT NULL,
idPlayer INTEGER NOT NULL,
idRole INTEGER,
phase INTEGER DEFAULT 0,
numPlayer INTEGER,
roadSheet VARCHAR(256),
PRIMARY KEY(idServer,idPlayer)
)ENGINE=InnoDB;

ALTER TABLE Players
  ADD CONSTRAINT FOREIGN KEY (idServer)
  REFERENCES Servers(idServer)
  ON DELETE CASCADE;

ALTER TABLE Players
  ADD CONSTRAINT FOREIGN KEY (idPlayer)
  REFERENCES Users(idUser)
  ON DELETE CASCADE;

ALTER TABLE Players
  ADD CONSTRAINT FOREIGN KEY (idRole)
  REFERENCES Role(idRole)
  ON DELETE CASCADE;

